### ISSUE TITLE
Uses 5.10 SDK

### ISSUE THREAD

**Issue by nedrichards** [flathub/io.github.janbar.noson#1]
I see the manifest uses the KDE 5.10 SDK which is based upon Qt 5.10. This is now out of security support and won't recieve further updates. It'd be good to move to either the 5.9 lts or the newer and fresher 5.11 SDK.

**Comment by janbar** [comment]
I will update the manifest to use the LTS. The app hasn't been fully tested with the latest framework.

**Comment by janbar** [comment]
fixed with commit 185f385fd50b11ab01e917f334f0a84c2a0fae06
